### ISSUE TITLE
rename "Revisions" on menu to "History" and limit

### ISSUE THREAD

**Issue by mfrederickson** [KPB-US/budgy#31]
Should be limited to one weeks worth of POSTED, REJECTED, CANCELLED entries, and no limit to items in another status.

**Comment by mfrederickson** [comment]
Show newest first

**Comment by techmastermike** [comment]
Redo models -> concerns -> approvals -> scope to include status = DRAFT revisions that are owned by the preparer or the preparer's peeps.

**Comment by techmastermike** [comment]
Rename Revisions to Revisions History and limit to 1 week (1.week.ago) using scope somehow and move to the right of the dashboard.

**Comment by mfrederickson** [comment]
@techmastermike 
![image](https://cloud.githubusercontent.com/assets/473165/16017728/9e30756e-314d-11e6-9ec0-cfb8d73d89c9.png)

**Comment by techmastermike** [comment]
User's own drafts should show in Dashboard.
