### ISSUE TITLE
Need two levels of finance roles

### ISSUE THREAD

**Issue by techmastermike** [KPB-US/budgy#36]
Finance Reviewers (Penny, et al.) - will first get the submission from the submitting director. Upon THEIR approval, it will go to:

Finance Approvers (Brandi, Craig) - can review AND approve

Optional: Finance Clerk - Post only rights in cancancan. Reviewers and Approvers should also have this right. Maybe.

**Comment by mfrederickson** [comment]
Will add a "finance-clerk" that will be used for data entry and reviewing.  Will continue using the "finance" for the approvals.

**Comment by mfrederickson** [comment]
refactoring approvals.  need to also update pdf
