### ISSUE TITLE
Give select users permissions to give other users various (finance) roles

### ISSUE THREAD

**Issue by techmastermike** [KPB-US/budgy#46]
In the case that finance clerk Penny is out of the office, Brandi (?) could then assign the finance clerk role to another user, or herself. This would be an alternative to asking IT to do it.

**Comment by mfrederickson** [comment]
@techmastermike and I discussed this issue and determined that the minuscule use-case this would satisfy was not worth the development time it would take to implement, especially since an alternate workaround exists where the user can be a member of multiple roles.
