### ISSUE TITLE
Director approval should not be required for directors

### ISSUE THREAD

**Issue by techmastermike** [KPB-US/budgy#8]

**Comment by mfrederickson** [comment]
How do we determine who a director is?  Some titles are 'Director', 'Chief', 'Assessor', etc.  So what we will do is assume that if their "manager" is the "Borough Mayor" then they are a director.

**Comment by mfrederickson** [comment]
The code will automatically mark the director's routing entry as approved if the director is the one that submits it.  When this occurs, an email should not be sent to the director.
